sudo: required
language: java
jdk: oraclejdk13
      
services:
- xvfb
- mysql

before_install:
  - sudo apt-get update
  - sudo apt-get install dbus-x11
  - export DISPLAY=:99.0
  - sleep 3
  - export CHROME_BIN=/usr/bin/google-chrome
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/bin
  
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo cp script.sql /usr/bin
  - sudo mysql_upgrade
  - sudo service mysql restart
  - mysql < /usr/bin/script.sql
  
script: 
- mvn clean
- mvn test
- mvn surefire:test -Dtest=DBUnitTestSQL

after_success: 
- mysql -e 'SHOW DATABASES;'
- mysql -e 'USE DBUnit; SHOW TABLES;'
- mysql -e 'select * from mysql.user;'


