ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS DBUnit;
USE DBUnit;
CREATE TABLE IF NOT EXISTS Alumnia(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(40) NOT NULL,
  lastName VARCHAR(40) NOT NULL,
  age INT NOT NULL,
  average FLOAT NOT NULL
);
